config/routes.rb
Enxoval_do_bebe::Application.routes.draw do
  get "home/index"

  resources :items do
		 member do
			get :choose
			put :unchoose
			post :make_choice
		 end
	end

  match 'user/edit' => 'users#edit', :as => :edit_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "home#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price, :user_id, :description, :user_name

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation, :name, :is_admin

  attr_accessor :password
  before_save :prepare_password


	has_many :items

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(params[:item])
    if @item.save
      flash[:notice] = "Successfully created item."
      redirect_to items_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      flash[:notice] = (params[:item][:user_name].present? ? "Prenda escolhida com sucesso" : "Successfully updated item.")
      redirect_to items_path
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "Successfully destroyed item."
    redirect_to items_url
  end

	def choose
		@item = Item.find(params[:id])
	end

	def make_choice
		@item = Item.find(params[:id])
		@item.user_name = params[:name]
		if @item.save
			flash[:notice] = "Prenda escolhida com sucesso"
			redirect_to items_path
		else
			flash[:error] = "Houve um problema a escolher a prenda, por favor tente outra vez."
			redirect_to choose_item_path(@item)
		end
	end	

	def unchoose
		@item = Item.find(params[:id])
		@item.user_name = ""
		if @item.save
			flash[:notice] = "Escolha removida com sucesso."
		else
			flash[:error] = "Ocorreu um erro na remocao da sua escolha."
		end
		redirect_to items_url
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default("/")
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
			if current_user && current_user != @user
				flash[:notice] = "Utilizador registado com sucesso."
				redirect_to users_path
			else
	      session[:user_id] = @user.id
	      flash[:notice] = "Thank you for signing up! You are now logged in."
  	    redirect_to "/"
			end
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile has been updated."
      redirect_to @user
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% title "Lista para o enxoval do Bebé da Alice e do Filipe" %>

<p>Olá Familia e Amigos, <br />
 Aproxima-se a chegada de um novo elemento da familia. </p>
<p>Por insistência de algumas pessoas decidimos fazer uma lista de prendas que poderão oferecer para o "enxoval" do bebé. Deverão acrescentar o nome à frente do item que pretendem oferecer e, se quiserem podem deixar mensagem.  Podem agrupar prendas por mais do que uma familia e/ou amigo!</p>
<p>Qualquer duvida não hesitem em contactar-nos!!</p>
<p>Desde já:  Muito obrigado!</p>
<p>Beijinhos,<br />
 Filipe, Alice e Bebé!</p>

<p><%= link_to "Lista de prendas", items_path %></p>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price, "Preço" %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description, "Descrição" %><br />
    <%= f.text_area :description %>
  </p>
	<p>
		<%= f.label :location, "Localização"%><br />
		<%= f.text_field :location %>
	</p>
  <p><%= f.submit %></p>
<% end %>

app/views/items/choose.html.erb
<% title "Escolher uma prenda" %>
<%= form_for @item do |f| %>
	<p>
		<strong>Nome da prenda</strong>
		<%= @item.name %>
	<p>
	<p>
		<%= f.label :user_name, "O seu nome"%> <br />
		<%= f.text_field :user_name %>
	</p>
	<p>
		<%= f.submit "Escoher" %>
	</p>
<% end %>
<p><%= link_to "Lista de prendas", items_path %></p>

app/views/items/edit.html.erb
<% title "Editar Prenda" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @item %> |
  <%= link_to "View All", items_path %>
</p>

app/views/items/index.html.erb
<% title "Lista de Prendas" %>

<table id="items_table">
  <tr>
    <th>Nome</th>
    <th>Preço</th>
    <th style="width:20%">Descrição</th>
		<th>Localização</th>
		<th>Estado</th>
		<th>Opções</th>
  </tr>
  <% for item in @items %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.price %></td>
      <td><%= item.description %></td>
			<td><%= item.location %></td>
			<td><%= raw (item.user_name.present? ? ( "Prenda escohida por #{h(item.user_name)}") : "Disponível") %></td>
			<td>
				<% if current_user && current_user.is_admin? %>
		      <%= link_to "Show", item %> |
  		    <%= link_to "Edit", edit_item_path(item) %> |
    		  <%= link_to "Destroy", item, :confirm => 'Are you sure?', :method => :delete %>
					<% if item.user_name.present? %>
					<%= link_to "Remover escolha", unchoose_item_path(item), :method => :put %>
					<% end %>
				<% elsif !item.user_name.present? %>
					<%= link_to "Escolher", choose_item_path(item) %>
	      <% end %>
			</td>
    </tr>
  <% end %>
</table>
<% if current_user && current_user.is_admin? %>
	<p><%= link_to "Nova Prenda", new_item_path %></p>
<% end %>

<style type="text/css">
table#items_table th {
	width: 150px
}
table#items_table td {
	text-align: left;
	border: 1px solid gray;
}
</style>

app/views/items/new.html.erb
<% title "Nova Prenda" %>

<%= render 'form' %>

<p><%= link_to "Back to List", items_path %></p>

app/views/items/show.html.erb
<% title "Prenda" %>

<p>
  <strong>Nome:</strong>
  <%= @item.name %>
</p>
<p>
  <strong>Preço:</strong>
  <%= @item.price %>
</p>
<p>
  <strong>Descrição:</strong>
  <%= @item.description %>
</p>
<% if current_user && current_user.is_admin? %>
	<p>
	  <strong>Escolhido por:</strong>
	  <%= @item.user_name.present? ? @item.user_name : "Ainda não foi escolhido por ninguém." %>
	</p>
<% end %>

<p>
	<% if current_user && current_user.is_admin? %>
	  <%= link_to "Edit", edit_item_path(@item) %> |
	  <%= link_to "Destroy", @item, :confirm => 'Are you sure?', :method => :delete %> |
	<% end %>
  <%= link_to "Ver todos", items_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
			<div style="float:right">
				<%= link_to "Início", root_path %> |
				<%= link_to 'Lista de prendas', items_path %> |
				<% if !current_user %>
					<%= link_to 'log in', login_path %>
				<% else %>
  				<%= link_to current_user.name, current_user %> |
					<% if current_user.is_admin? %>
						<%= link_to "Registar novo utilizador", signup_path %> |
					<% end %>
					<%= link_to 'log out', logout_path %>
        <% end %>
      </div>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <div style="clear:both">
	      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
	<% if current_user && current_user.is_admin? %>
  	<p>
			<%= f.label :is_admin %>
			<%= f.check_box :is_admin%>
		</p>
	<% end %>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% title "Utilizadores" %>

<table id="users_table">
  <tr>
    <th>Nome</th>
    <th>Username</th>
    <th>E-mail</th>
		<th>Número de items escolhidos</th>
		<th>Opções</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
			<td><%= user.items.count %></td>
			<td>
				<% if current_user.is_admin? %>
		      <%= link_to "Show", user %> |
  		    <%= link_to "Edit", edit_user_path(user) %> |
    		  <%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %>
	      <% end %>
			</td>
    </tr>
  <% end %>
</table>
<% if current_user.is_admin? %>
	<p><%= link_to "Novo utilizador", new_user_path %></p>
<% end %>

<style type="text/css">
table#users_table th {
	width: 150px
}
table#users_table td {
	text-align: center
}
</style>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<% title "Utilizador" %>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>E-mail</strong>
  <%= @user.email %>
</p>
<p>
	<% if current_user.is_admin? || current_user == @user %>
	  <%= link_to "Edit", edit_user_path(@user) %> 
 	<% end %>
	<% if current_user.is_admin? %>
		|
	  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
	  <%= link_to "Ver todos", users_path %>
	<% end %>
</p>
<% if @user == current_user || current_user.is_admin? %>
	<div>
		<h4>Prendas escolhidos</h4>
		<% if @user.items.present? %>
			<table id="users_table">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Preço</th>
						<th>Descrição</th>
						<th>Localização</th>
					</tr>
				</thead>
				<tbody>
					<% for item in @user.items %>
						<tr>
							<td><%= item.name %></td>
							<td><%= item.price %></td>
							<td><%= item.description %></td>
							<td><%= item.location %></td>
							<% if current_user == @user %>
								<td><%= link_to "Remover escolha", unchoose_item_path(item), :method => :put %></td>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% else %>
			<p>Não escolheu nenhuma prenda..</p>
		<% end %>
	</div>
<% end %>


<style type="text/css">
table#users_table th {
	width: 150px
}
table#users_table td {
	text-align: center
}
</style>